version: "3.7"

services:
#  api:
#    container_name: commanderapi
#    build: .
#    ports:
#      - 12000:80
#      - 12001:443
#      - 5000:5000
#      - 5001:5001
#    depends_on:
#      - db
#    restart: on-failure
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+80
#      - ASPNETCORE_HTTPS_PORT=44311
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=mcdan2021
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
#    volumes:
#      - ./conf.d/https/:/https/
  
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5400:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: ~